language: ruby
cache: bundler
sudo: false
rvm:
  - 3.2.0
  - 3.1.3
  - 3.0.5
matrix:
  fast_finish: true
before_install: gem update --remote bundler
install:
  - bundle install --retry=3
gemfile:
  - gemfiles/rails_6.1.gemfile
  - gemfiles/rails_7.0.gemfile
script:
  - 'bundle exec rake spec'
  - 'bundle exec rubocop'
addons:
  code_climate:
    repo_token: 344f2a60a2920e96f71877b87829836b01a44e1e94463cde54e2c54e8f389f79
